# Generated by Django 3.2.13 on 2022-06-26 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videochat.user')),
            ],
        ),
    ]
